### ISSUE TITLE
Update copy

### ISSUE THREAD

**Issue by cheapwebmonkey** [civicdata/brigade-onboarding#3]
**Update all copy**
Use CDA specific copy and verbiage

**Describe the solution you'd like**
remove all brigade and CfA specific terms like "brigade" and "captains"
remove all instances of OpenOakland and replace with Civic Data Alliance

**Comment by LoganArnett** [comment]
Are you able to elaborate on this issue any further? I would like to help with this issue

**Comment by cheapwebmonkey** [comment]
@LoganArnett you'd go thru the copy and replace all instances of the word "brigade" with "organization", all instances of the word "captain/s" with "member/s" all instances of the word "OpenOakland" with "Civic Data Alliance" and all instances of "OO" with "CDA" 

thank you 👍
